### ISSUE TITLE
settings.debug == false ? '' : '--debug'

### ISSUE THREAD

**Issue by xhliu** [scrypt-sv/scryptlib#31]
Expected: this will cause to be in debug mode when `settings.debug` not explicitly set (undefined)?
https://github.com/scrypt-sv/scryptlib/blob/22e00e3c52ffd9298864181fe950a254c0776e87/src/compilerWrapper.ts#L110

**Comment by freedomhero** [comment]
It's an intended action which will give debug mode asm by default for now.
